apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-ai-platform.fullname" . }}-frontend-svc
  labels:
    {{- include "todo-ai-platform.labels" . | nindent 4 }}
    app: todo-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-ai-platform.selectorLabels" . | nindent 4 }}
    app: todo-frontend