apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-ai-platform.fullname" . }}-notification-service-svc
  labels:
    {{- include "todo-ai-platform.labels" . | nindent 4 }}
    app: notification-service
spec:
  type: {{ .Values.notificationService.service.type }}
  ports:
    - port: {{ .Values.notificationService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-ai-platform.selectorLabels" . | nindent 4 }}
    app: notification-service