apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-ai-chatbot.fullname" . }}-frontend
  labels:
    {{- include "todo-ai-chatbot.labels" . | nindent 4 }}
    app: todo-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "todo-ai-chatbot.selectorLabels" . | nindent 4 }}
    app: todo-frontend